
package com.tr.rdss.generic.model.iqm.concordance.http.session_client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HttpSessionIQMService", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HttpSessionIQMService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.InitResponse")
    @Action(input = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/initRequest", output = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/initResponse")
    public void init(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "close", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.Close")
    @ResponseWrapper(localName = "closeResponse", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.CloseResponse")
    @Action(input = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/closeRequest", output = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/closeResponse")
    public void close();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransactionStatus", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.GetTransactionStatus")
    @ResponseWrapper(localName = "getTransactionStatusResponse", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.GetTransactionStatusResponse")
    @Action(input = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/getTransactionStatusRequest", output = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/getTransactionStatusResponse")
    public int getTransactionStatus();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "beginTransaction", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.BeginTransaction")
    @ResponseWrapper(localName = "beginTransactionResponse", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.BeginTransactionResponse")
    @Action(input = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/beginTransactionRequest", output = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/beginTransactionResponse")
    public void beginTransaction();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "commitTransaction", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.CommitTransaction")
    @ResponseWrapper(localName = "commitTransactionResponse", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.CommitTransactionResponse")
    @Action(input = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/commitTransactionRequest", output = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/commitTransactionResponse")
    public void commitTransaction();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "rollbackTransaction", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.RollbackTransaction")
    @ResponseWrapper(localName = "rollbackTransactionResponse", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.RollbackTransactionResponse")
    @Action(input = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/rollbackTransactionRequest", output = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/rollbackTransactionResponse")
    public void rollbackTransaction();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQuoteVOByPermId", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.GetQuoteVOByPermId")
    @ResponseWrapper(localName = "getQuoteVOByPermIdResponse", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.GetQuoteVOByPermIdResponse")
    @Action(input = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/getQuoteVOByPermIdRequest", output = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/getQuoteVOByPermIdResponse")
    public String getQuoteVOByPermId(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveEntityVO", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.SaveEntityVO")
    @ResponseWrapper(localName = "saveEntityVOResponse", targetNamespace = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/", className = "com.tr.rdss.generic.model.iqm.concordance.http.session_client.SaveEntityVOResponse")
    @Action(input = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/saveEntityVORequest", output = "http://session.http.concordance.iqm.model.generic.rdss.tr.com/HttpSessionIQMService/saveEntityVOResponse")
    public Long saveEntityVO(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
